name: Deploy to cPanel

on:
   push:
      branches:
         - deploy # Update if the default branch is different

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - name: Setup Node.js
           uses: actions/setup-node@v2
           with:
              node-version: '20'

         - name: Install dependencies
           run: npm ci

         - name: Build project
           run: npm run build

         - name: Debug Output
           run: |
              echo "Working Directory:"
              pwd
              echo "Files in Directory:"
              ls -la ./out/

         - name: Deploy to cPanel
           uses: SamKirkland/FTP-Deploy-Action@4.3.3
           with:
              server: ${{ secrets.FTP_SERVER }}
              username: ${{ secrets.FTP_USERNAME }}
              password: ${{ secrets.FTP_PASSWORD }}
              local-dir: ./out/ # Update if the build directory is different
              server-dir: /
