name: Deploy to cPanel
on:
   push:
      branches:
         - last-version

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - name: Setup Node.js
           uses: actions/setup-node@v2
           with:
              node-version: '20'

         - name: Install dependencies
           run: npm ci

         - name: Build project
           run: npm run build && npm run postbuild

         - name: Deploy to cPanel
           uses: SamKirkland/FTP-Deploy-Action@4.3.3
           with:
              server: ${{ secrets.FTP_SERVER }}
              username: ${{ secrets.FTP_USERNAME}}
              password: ${{ secrets.FTP_PASSWORD }}
              local-dir: ./out/
              server-dir: /
